Lab_Routing_With_MVC_9/Models/ErrorViewModel.cs
namespace Lab_Routing_With_MVC_9.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab_Routing_With_MVC_9/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace Lab_Routing_With_MVC_9.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            string? controller = RouteData.Values["controller"]!.ToString();
            string? action = RouteData.Values["action"]!.ToString();
            StringBuilder sb = new StringBuilder();
            sb.Append($"<html><ul>");
            sb.Append($"<li>Controller: {controller}</li>");
            sb.Append($"<li>Action: {action}</li>");
            sb.Append("</ul></html>");
            return Content(sb.ToString(), "text/html");
        }

        public IActionResult Indexsetup()
        {
            string? controller = RouteData.Values["controller"]!.ToString();
            string? action = RouteData.Values["action"]!.ToString();
            StringBuilder sb = new StringBuilder();
            sb.Append($"<html><ul>");
            sb.Append($"<li>Controller: {controller}</li>");
            sb.Append($"<li>Action: {action}</li>");
            sb.Append("</ul></html>");
            return Content(sb.ToString(), "text/html");
        }
    }
}

Lab_Routing_With_MVC_9/Controllers/HomeController.cs
using Lab_Routing_With_MVC_9.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab_Routing_With_MVC_9.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab_Routing_With_MVC_9/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using System.Text;

namespace Lab_Routing_With_MVC_9.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Buy()
        {
            string? controller = RouteData.Values["controller"]!.ToString();
            string? action = RouteData.Values["action"]!.ToString();
            StringBuilder sb = new StringBuilder();
            sb.Append($"<html><ul>");
            sb.Append($"<li>Controller: {controller}</li>");
            sb.Append($"<li>Action: {action}</li>");
            sb.Append("</ul></html>");
            return Content(sb.ToString(), "text/html");
        }
    }
}

Lab_Routing_With_MVC_9/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace Lab_Routing_With_MVC_9.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult settings(int? id)
        {
            string? controller = RouteData.Values["controller"]!.ToString();
            string? action = RouteData.Values["action"]!.ToString();
            //string? id = RouteData.Values["id"]!.ToString();
            StringBuilder sb = new StringBuilder();
            sb.Append($"<html><ul>");
            sb.Append($"<li>Controller: {controller}</li>");
            sb.Append($"<li>Action    : {action}</li>");
            sb.Append($"<li>Id        : {id}</li>");
            sb.Append("</ul></html>");
            return Content(sb.ToString(), "text/html");
        }
    }
}

Lab_Routing_With_MVC_9/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <h3>LINK:</h3>
    <a href="/NewOrder">NewOrder</a>
    <a asp-controller="Shop" asp-action="Buy" class="btn btn-sm btn-primary">NewOrder_Tag_Helper</a>
    <a asp-controller="Home" asp-action="Error" class="btn btn-sm btn-info">Home/Error</a>
    <a href="/home/privacy" class="btn btn-sm btn-danger">Home/Privacy_ERROR</a>
    <a href="/admin/index" class="btn btn-sm btn-danger">Admin/Index_ERROR</a>
    <a asp-controller="Admin" asp-action="IndexSetup" class="btn btn-sm btn-info">Admin/IndexSetup</a>
    <a asp-controller="User" asp-action="Settings" asp-route-id=5 class="btn btn-sm btn-info">User/Setting/5</a>
    <a href="/user/settings/1000" class="btn btn-sm btn-danger">User/Setting/1000_ERROR</a>
    <a asp-controller="User" asp-action="Settings" asp-route-id=999 class="btn btn-sm btn-primary">User/Setting/999</a>

</div>

Lab_Routing_With_MVC_9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab_Routing_With_MVC_9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab_Routing_With_MVC_9.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab_Routing_With_MVC_9</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lab_Routing_With_MVC_9 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>